//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Demo.Framework.Data;

namespace Dome.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class CrmDbEntities : BaseDbContext
    {
        public CrmDbEntities()
            : base(DbConnection.CrmDb)
        {
            Database.SetInitializer<CrmDbEntities>(null);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sys_Area> Sys_Area { get; set; }
        public DbSet<Sys_CodeMaster> Sys_CodeMaster { get; set; }
        public DbSet<Sys_Department> Sys_Department { get; set; }
        public DbSet<Sys_Login> Sys_Login { get; set; }
        public DbSet<Sys_Position> Sys_Position { get; set; }
        public DbSet<Sys_Powers> Sys_Powers { get; set; }
        public DbSet<Sys_Resource> Sys_Resource { get; set; }
        public DbSet<Sys_Role_Relation> Sys_Role_Relation { get; set; }
        public DbSet<Sys_Roles> Sys_Roles { get; set; }
        public DbSet<Sys_Users> Sys_Users { get; set; }
    }
}
