//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dome.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_CodeMaster
    {
        public int 类型编号 { get; set; }
        public string 键 { get; set; }
        public string 值 { get; set; }
        public string Column_1 { get; set; }
        public string Column_2 { get; set; }
        public string Column_3 { get; set; }
        public string Description { get; set; }
        public string ForTable { get; set; }
        public string ForColumn { get; set; }
    }
}
