//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dome.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Login
    {
        public int UID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
